name: Week 1 Mission

on: [issues]

jobs:
  job-1-generator:
    runs-on: ubuntu-latest
    #Job Outputs
    outputs: 
      my-name: ${{ steps.step1.outputs.name }}
      my-age: ${{ steps.step2.outputs.age }}

    steps:
      - name: Generate my Name
        id: step1
        run: echo "name=Johann" >> "$GITHUB_OUTPUT"

      - name: Generate Age
        id: step2
        run: echo "age=22" >> "$GITHUB_OUTPUT"

  job-2-receiver:
    if: github.actor == 'j4rmenkell' 
    runs-on: ubuntu-latest

    needs: job-1-generator

    steps:
      - name: Show Name
        run: echo "The name is ${{ needs.job-1-generator.outputs.my-name }}"
      - name: Show Age
        run: echo "The age of  ${{ needs.job-1-generator.outputs.my-name }} is  ${{ needs.job-1-generator.outputs.my-age }}"

        
    
    
      
