name: Repo Dispatch example

on: 
  repository_dispatch: 
    types: [test-my-payload, hello]

jobs:
  show-payload:
    runs-on: ubuntu-latest
    steps:
      - name: Show payload 
        run: |
          echo "Event name: ${{ github.event.action }}"
          echo "Here is the message: ${{ github.event.client_payload.message }}"
    